// src/components/common/Loading.jsx
import Slide from "./Slide";

export default function Loading() {
    return (
        <Slide>
            <div className="loading">
                <svg width='200' height='200' viewBox="-75 -75 150 150">
                    <Circle x={-2} y={-10} color={"cyan"} />
                    <Circle x={2} y={-10} color={"red"} />
                    <Circle x={0} y={-10} color={"black"} />
                </svg>
            </div>
        </Slide>

    )
}

function Circle({ x, y, color }) {
    return (
        <circle
            r="5"
            cx={x}
            cy={y}
            strokeWidth="5"
            fill={color}
        >
            <animateTransform
                attributeName='transform'
                type='rotate'
                from="0 0 0"
                to="360 0 0"
                repeatCount='indefinite'
                dur='2s'
                calcMode='linear'
            />
        </circle>)
}

// src/contact/Loading.svelte
<svg width="24" height="24" viewBox="2.00 2.00 20 20" xmlns="http://www.w3.org/2000/svg">
  <g>
    <circle r="3" cx="17" cy="12" fill="white" />
    <circle r="3" cx="7" cy="12" fill="white" />
    <circle r="3" cx="12" cy="17" fill="white" />
    <circle r="3" cx="12" cy="7" fill="white" />

    <animateTransform
      dur="2s"
      attributeName="transform"
      type="rotate"
      from="0 12 12"
      to="360 12 12"
      repeatCount="indefinite"
    />
  </g>
</svg>
